name: Intention Generator Components
run-name: ${{ github.actor }} is deploying the project
on: 
  push:
    branches:
      - main
      - production
jobs:
  Deploy-To-Servers:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{secrets.SSH}}
          source: "./current/*"
          target: "/home/ci/intentionGenerator/current"
      - name: Purge Cache
        run : |
          curl --fail --show-error -X POST "https://api.cloudflare.com/client/v4/zones/${{secrets.ZONE_ID}}/purge_cache" \
                -H "Authorization: Bearer ${{secrets.PURGE_CACHE_TOKEN}}" \
                -H "Content-Type: application/json" \
                --data '{"purge_everything":true}'
